apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: servicecatalog-controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - servicecatalog.k8s.io
  resources: ["*"]
  verbs: ["*"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: servicecatalog-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: servicecatalog-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: servicecatalog-controller-manager
subjects:
- kind: ServiceAccount
  name: servicecatalog-controller-manager
  namespace: {{ .Release.Namespace }}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "fullname" . }}-controller-manager
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-controller-manager
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-controller-manager
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      serviceAccountName: servicecatalog-controller-manager
      containers:
      - name: controller-manager
        image: {{ .Values.controllerManager.image }}
        imagePullPolicy: {{ .Values.controllerManager.imagePullPolicy }}
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
        args:
        - --port=8080
        - -v={{ .Values.controllerManager.verbosity }}
        - --resync-interval={{ .Values.controllerManager.resyncInterval }}
        {{- if not .Values.useAggregator }}
        - --service-catalog-api-server-url
        {{- if .Values.apiserver.insecure }}
        - http://{{ template "fullname" . }}-apiserver
        {{- else }}
        - https://{{ template "fullname" . }}-apiserver
        {{- end }}
        {{- end }}
        {{ if .Values.controllerManager.brokerRelistIntervalActivated -}}
        - --broker-relist-interval={{ .Values.controllerManager.brokerRelistInterval }}
        {{- end }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: service-catalog-cert
          mountPath: /etc/service-catalog-ssl
          readOnly: true
        readinessProbe:
          httpGet:
            port: 8080
            path: /healthz
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            port: 8080
            path: /healthz
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
      volumes:
      - name: service-catalog-cert
        secret:
          secretName: {{ template "fullname" . }}-apiserver-cert
          items:
          - key: tls.crt
            path: apiserver.crt
